#/etc/hosts
x-hosts: &hosts
  extra_hosts:
    - ip.www    :${NGINX_IP}
    - ip.host   :${HOST_IP}

services:
  ### NGINX ##############################################################################
  nginx:
    build: ./nginx
    container_name: nginx
    privileged: true
    expose:
      - 80
      - 443
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
      - ${NGINX_HOST_HTTPS_PORT}:443
    restart: always
    volumes:
      # nginx默认配置文件
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ${WEB_ROOT_PATH}:/var/www/
      - ${NGINX_LOG_PATH}:/var/log/nginx/
    networks:
      backend:
        ipv4_address: ${NGINX_IP}

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ${WEB_ROOT_PATH}/certbot/:/var/www/certbot/:rw
      - ./nginx/ssl/:/etc/letsencrypt/:rw
    networks:
      backend:
        ipv4_address: ${CERTBOT_IP}

  mysql:
    build:
      context: ./mysql
      args:
        - VERSION=${MYSQL_VERSION}
        - ENABLE_DEBUG_LOG=${ENABLE_DEBUG}
#    M1 需要指定 platform
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${MYSQL_TIMEZONE}
    volumes:
      # 数据文件
      - ${MYSQL_DATA_PATH}:/var/lib/mysql
      # 日志文件
      - ${MYSQL_LOG_PATH}:/var/log/mysql
    command: --default-authentication-plugin=mysql_native_password ${MYSQL_CONF_COMMAND}
    restart: always
    privileged: true
    expose:
      - 3306
    #ports:
    #  - ${MYSQL_PORT}:3306
    networks:
      backend:
        ipv4_address: ${MYSQL_IP}

  redis:
    build:
      context: ./redis
      args:
        - VERSION=${REDIS_VERSION}
    container_name: redis
    command: redis-server /etc/redis/redis.conf
    restart: always
    expose:
      - 6379
    #ports:
     # - ${REDIS_PORT}:6379
    volumes:
      - ${REDIS_DATA_PATH}:/data
      - ${REDIS_CONF_PATH}:/etc/redis/redis.conf
    networks:
      backend:
        ipv4_address: ${REDIS_IP}

  php56:
    build:
      context: ./php56
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
    container_name: php56
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9056
    #ports:
    #  - "9056:9056"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php56/config/php.ini:/usr/local/etc/php/php.ini
      - ./php56/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php56/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php56/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php56/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php56/:/var/log/php/
      - ${PHP_LOG_PATH}/php56/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP56_IP}

  php71:
    build:
      context: ./php71
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=true
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
    container_name: php71
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9071
    #ports:
    #  - "9071:9071"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php71/config/php.ini:/usr/local/etc/php/php.ini
      - ./php71/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php71/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php71/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php71/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php71/:/var/log/php/
      - ${PHP_LOG_PATH}/php71/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP71_IP}

  php72:
    build:
      context: ./php72
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
    container_name: php72
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9072
    #ports:
    #  - "9072:9072"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php72/config/php.ini:/usr/local/etc/php/php.ini
      - ./php72/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php72/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php72/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php72/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php72/:/var/log/php/
      - ${PHP_LOG_PATH}/php72/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP72_IP}

  php73:
    build:
      context: ./php73
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
    container_name: php73
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9073
    #ports:
    #  - "9073:9073"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php73/config/php.ini:/usr/local/etc/php/php.ini
      - ./php73/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php73/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php73/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php73/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php73/:/var/log/php/
      - ${PHP_LOG_PATH}/php73/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP73_IP}

  php74:
    build:
      context: ./php74
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
    container_name: php74
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9074
    #ports:
    #  - "9074:9074"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php74/config/php.ini:/usr/local/etc/php/php.ini
      - ./php74/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php74/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php74/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php74/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php74/:/var/log/php/
      # 应用日志
      - ${PHP_LOG_PATH}/php74/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP74_IP}

  php80:
    build:
      context: ./php80
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
    container_name: php80
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9080
    #ports:
    #  - "9080:9080"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php80/config/php.ini:/usr/local/etc/php/php.ini
      - ./php80/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php80/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php80/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php80/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php80/:/var/log/php/
      # 应用日志
      - ${PHP_LOG_PATH}/php80/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP80_IP}

  php81:
    build:
      context: ./php81
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
        - EXT_KAFKA=true
    container_name: php81
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9081
      - 8881
    #ports:
    #  - "9081:9081"
    #  - "8881:8881"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php81/config/php.ini:/usr/local/etc/php/php.ini
      - ./php81/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php81/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php81/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php81/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php81/:/var/log/php/
      # 应用日志
      - ${PHP_LOG_PATH}/php81/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP81_IP}
  php82:
    build:
      context: ./php82
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=true
        - EXT_PROTOBUF=true
        - EXT_MEMCACHED=true
        - EXT_SWOOLED=true
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
        - EXT_KAFKA=true
    container_name: php82
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9082
      - 8882
    #ports:
    #  - "9082:9082"
    #  - "8882:8882"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php82/config/php.ini:/usr/local/etc/php/php.ini
      - ./php82/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php82/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php82/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php82/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php82/:/var/log/php/
      # 应用日志
      - ${PHP_LOG_PATH}/php82/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP82_IP}
  php83:
    build:
      context: ./php83
      args:
        - EXT_GD=false
        - EXT_REDIS=false
        - EXT_GRPC=false
        - EXT_PROTOBUF=false
        - EXT_MEMCACHED=false
        - EXT_SWOOLED=false
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
        - EXT_KAFKA=false
    container_name: php83
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9083
      - 8883
    #ports:
    #  - "9083:9083"
    #  - "8883:8883"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php83/config/php.ini:/usr/local/etc/php/php.ini
      - ./php83/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php83/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php83/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php83/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php83/:/var/log/php/
      # 应用日志
      - ${PHP_LOG_PATH}/php83/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP83_IP}
  php84:
    build:
      context: ./php84
      args:
        - EXT_GD=true
        - EXT_REDIS=true
        - EXT_GRPC=true
        - EXT_PROTOBUF=true
        - EXT_MEMCACHED=true
        - EXT_SWOOLED=true
        - ENABLE_XDEBUG=${ENABLE_DEBUG}
        - ENABLE_LOCALIZE=${ENABLE_LOCALIZE}
        - EXT_KAFKA=true
    container_name: php84
    privileged: true
    restart: always
    cap_add:
      - SYS_PTRACE
    expose:
      - 9084
      - 8884
    #ports:
    #  - "9084:9084"
    #  - "8884:8884"
    #/etc/hosts
    <<: *hosts
    volumes:
      # php 配置文件
      - ./php84/config/php.ini:/usr/local/etc/php/php.ini
      - ./php84/config/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - ./php84/config/php-fpm.d:/usr/local/etc/php-fpm.d
      - ${DATA_ROOT_PATH}/php84/id_rsa.pub:/root/.ssh/id_rsa.pub
      - ${DATA_ROOT_PATH}/php84/id_rsa:/root/.ssh/id_rsa
      # 项目代码
      - ${WEB_ROOT_PATH}:/var/www/
      # php-fpm日志
      - ${PHP_LOG_PATH}/php84/:/var/log/php/
      # 应用日志
      - ${PHP_LOG_PATH}/php84/app/:/data/log/
    networks:
      backend:
        ipv4_address: ${PHP84_IP}
networks:
  backend:
    external: true
